stages:
  - test

unit_test:
  stage: test
  only:
    - master
  script:
    - npm install
    - npm run test
  after_script:
    - echo "Unit tests completed"
  except:
    - schedules

blocking_push:
  stage: test
  only:
    - master
  script:
    - echo "Blocking push if tests failed"
  rules:
    - exists:
        - coverage/
      when: on_failure
